project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 1

logging: 
  name: mcq_gpt-4o-mini_easy_4fps_firstframe
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  # split: demo
  split: easy
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "0"

lmm:
  api: openai
  fps: 8
  model: gpt-4o-mini
  video_representation: first_frame
  seed: ${seed}
  max_imgs: 140
