project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 1

logging: 
  name: mcq_gemini-pro_easy_8fps_8geminifps
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  # split: demo
  split: easy
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "0"

lmm:
  api: gemini 
  fps: 8
  fps_gemini: 8
  model: models/gemini-1.5-pro
  # model: models/gemini-1.5-flash
  video_representation: video
  seed: ${seed}
