project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 2

logging: 
  name: mode2-llavavideo_diving_6fps
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  split: diving
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "0"

lmm:
  api: llavavideo
  fps: 6
  model: lmms-lab/LLaVA-Video-7B-Qwen2
  video_representation: llavavideo
  seed: ${seed}
