project: viddiff_0
seed: 0
debug: 0
do_eval: 1 
eval_mode: 0

logging: 
  name: qwen_surgery_2fps
  results_dir: lmms/results/${logging.name}/seed_${seed}
  overwrite_ok: True
  verbose: 1 

data:
  split: surgery
  debug: ${debug}
  eval_mode: ${eval_mode}  
  subset_mode: "0"

lmm:
  api: qwen
  fps: 2
  model: "Qwen/Qwen2-VL-7B-Instruct"
  video_representation: video
  seed: ${seed}
